[render]
source = "sample-site/"
target = "sample-output/"
delete_target_dir = true
engines = ["markdown"]

[render.engine.markdown]
extensions = ["tables", "md_in_html"]
html_template = "microsite/render/templates/markdown.html.j2"
pretty_html = true
rewrite_md_extensions = true
rewrite_md_urls = true
stylesheet = "microsite/render/styles/plain-white.css"
stylesheet_target_name = "style.css"
title = "Microsite Sample Site"

[render.engine.markdown.index."page2.md"]
title = "Microsite Sample Site Page 2"

[render.engine.markdown.index."dir/page3.md"]
title = "Microsite Sample Site Subdirectory Example"

[publish]
source = "sample-output/"

[publish.targets.s3website-prod]
engine = "tbp_s3website"
project_name = "microsite"
project_description = "MicroSite Sample Site"
aws_region = 'us-east-1'
pulumi_state_backend = "s3"  # or "cloud"
pulumi_access_token_file = ""  # Ignored when pulumi_state_backend is not "cloud"
pulumi_passphrase_file = "sample-site.pulumi.pass"
pulumi_log = "pulumi.log"
pulumi_error_log = "pulumi.err"
pulumi_stack_name = "prod"
pulumi_state_s3_bucket = "microsite-sample-site-pulumi"
publish_bucket = "microsite-sample-site"
enable_cloudfront = false
work_dir = "tbpulumi-s3website-prod"
persist_work_dir = false
index_document = "index.html"